cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://erudio.com.br
spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projetoweb?useTimezone=true&serveTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: true
    spring:
  flyway:
    baseline-on-migrate: true
spring-doc: 
   pathsToMatch: /api/**/v1/**
   swagger-ui:
     use-root-path: true
